name: Compressor

on: [push]

env:
  FILE_URL: https://mirror.rahul137.workers.dev/Alpha.gz 
  FILE_NAME: alpha-c2.apk
  TZ: Asia/Kolkata
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Setup
         run: |
           sudo apt install expect wget gzip aria2 -y

       - name: Download File
         run: |
              mkdir -p file
              cd file
              echo "Downloading your file. wait... it can take some seconds/minutes"
              aria2c  $FILE_URL

       - name: Decompress File
         run: |
              cd file
              ls
              echo "Decompressing your file. wait... it will take some seconds"
              gzip -dv *.gz
              ls
       
       - name: Compress File
         run: |
              cd file
              ls
              echo "Compressing your file. wait... it can take some minutes"
              xz -fev9 *
              ls

       - name: Upload File
         run: |
              cd file
              echo "Uploading your file. wait... it can take some seconds/minutes"
              ls
              expect -c " 
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"cd ${{ secrets.SFDIR }}\r\"
              set timeout -1
              send \"put *.xz\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
