name: Compressor

on: [push]

env:
  FILE_URL: https://github-releases.githubusercontent.com/379970004/6dabfca6-26bc-4a40-824e-73d521fbab84?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20210827%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210827T130504Z&X-Amz-Expires=300&X-Amz-Signature=b7433706b713bed5c51c01129322f9918ccb32aca4fe6ffe3eb766bad10c9f91&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=379970004&response-content-disposition=attachment%3B%20filename%3Dsystem.img&response-content-type=application%2Foctet-stream
  FILE_NAME: Ancient-5.5-weebo.img
  TZ: Asia/Kolkata
jobs:
  Compress:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Setup
         run: |
           sudo apt install expect aria2 -y

       - name: Download File
         run: |
              mkdir -p file
              cd file
              if [ -z "$FILE_URL" ]; then
              echo "Enter url of file to download"
              exit 1;
              else echo "Downloading your file. wait... it can take some seconds/minutes"
              aria2c -c --max-tries=0 --max-file-not-found=0 $FILE_URL;
              fi
       
       - name: Compress File
         run: |
              cd file
              ls
              echo "Compressing your file. wait... it can take some minutes"
              if [ -z "$FILE_NAME" ]; 
              then xz -fev9 *; 
              else xz -cfev9 * > $FILE_NAME.xz ; 
              fi
              ls

       - name: Upload File
         run: |
              cd file
              echo "Uploading your file. wait... it can take some seconds/minutes"
              ls
              expect -c " 
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"cd ${{ secrets.SFDIR }}\r\"
              set timeout -1
              send \"put *.xz\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
