name: Compressor

on: [push]

env:
  FILE_URL: https://mirror.rahul137.workers.dev/BGMI/com.pubg.imobile/main.15255.com.pubg.imobile.obb(vndk28%252C30)-2021.06.15-LZY-SGSI/SGSI/system.img
  FILE_NAME:
  TZ: Asia/Kolkata
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Setup
         run: |
           sudo apt install expect aria2 -y

       - name: Download File
         run: |
              mkdir -p file
              cd file
              if [ -z "$FILE_URL" ]; then
              echo "Enter url of file to download"
              exit 1;
              else echo "Downloading your file. wait... it can take some seconds/minutes"
              aria2c -c -m 0 $FILE_URL;
              fi
       
       - name: Compress File
         run: |
              cd file
              ls
              echo "Compressing your file. wait... it can take some minutes"
              if [ -z "$FILE_NAME" ]; 
              then xz -fev9 *; 
              else xz -cfev9 * > $FILE_NAME.xz ; 
              fi
              ls

       - name: Upload File
         run: |
              cd file
              echo "Uploading your file. wait... it can take some seconds/minutes"
              ls
              expect -c " 
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"cd ${{ secrets.SFDIR }}\r\"
              set timeout -1
              send \"put *.xz\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
