name: Compressor

on: [push]

env:
  FILE_URL: https://mirror.rahul137.workers.dev/Dot-t-AB-11-20210610-RK137GSI.img.gz 
  FILE_NAME: Dot-c
  F_NAME: Dot-t-AB-11-20210610-RK137GSI.img
  TZ: Asia/Kolkata
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Setup
         run: |
           sudo apt install expect wget gzip aria2 -y

       - name: Download File
         run: |
              mkdir -p file
              echo "Downloading your file. wait... it can take some seconds/minutes"
              aria2c -o "file/$FILE_NAME.gz"  $FILE_URL

       - name: Decompress File
         run: |
              cd file
              ls
              echo "Decompressing your file. wait... it will take some seconds"
              gzip -dv $FILE_NAME.gz
              ls
              mv $FILE_NAME $F_NAME
              ls
              mkdir -p final
              mv $F_NAME final
              cd final
              ls
       
       - name: Compress File
         run: |
              cd file/final
              ls
              echo "Compressing your file. wait... it can take some minutes"
              xz -cfev9 * > $FILE_NAME.xz
              ls

       - name: Upload File
         run: |
              cd file/final
              echo "Uploading your file. wait... it can take some seconds/minutes"
              ls
              expect -c " 
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"cd ${{ secrets.SFDIR }}\r\"
              set timeout -1
              send \"put $FILE_NAME.xz\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
