name: Compressor

on: [push]

env:
  FILE_URL: https://mirror.rahul137.workers.dev/Floko-tl-RK137GSI.zip 
  FILE_NAME: test-file.zip
  TZ: Asia/Kolkata
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Setup
         run: |
           sudo -E apt-get update
           sudo apt install expect -y
           sudo apt-get install -y wget gzip
           unzip -h
