name: Compressor

on: [push]

env:
  FILE_URL: https://mirror.rahul137.workers.dev/blueline-spb2.210513.007-factory-6c2e7c7f/blueline-spb2.210513.007/image-blueline-spb2.210513.007.zip 
  FILE_NAME: test-file.gz
  ZIP_NAME: file.zip
  TZ: Asia/Kolkata
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           sudo -E apt-get update
           sudo apt install expect -y
           sudo apt-get install -y wget gzip
       
       - name: Download File
         run: |
              mkdir -p file
              wget -U "Mozilla/5.0" $FILE_URL -O "file/$ZIP_NAME"
       
       - name: Compress and upload 
         run: |
              cd file
              ls
              gzip -f -r $ZIP_NAME > $FILE_NAME
              expect -c " 
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"cd ${{ secrets.SFDIR }}\r\"
              set timeout -1
              send \"put $FILE_NAME\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
