name: Compressor

on: [push]

env:
  FILE_URL: https://mirror.rahul137.workers.dev/Pixel3-b2-S-20210610-RK137SGSI.zip 
  FILE_NAME: Pixel3-b2-S
  TZ: Asia/Kolkata
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Setup
         run: |
           sudo apt install expect -y
           sudo apt-get install -y wget

       - name: Download File
         run: |
              mkdir -p file
              wget -U "Mozilla/5.0" $FILE_URL -O "file/$FILE_NAME.zip"
              cd file
              mkdir -p final
       - name: Decompress File
         run: |
              cd file
              ls
              unzip -q $FILE_NAME -d ./final
              cd final
              ls
       
       - name: Compress and Upload 
         run: |
              cd file/final
              ls
              tar cJf $FILE_NAME.xz *
              ls
              expect -c " 
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"cd ${{ secrets.SFDIR }}\r\"
              set timeout -1
              send \"put $FILE_NAME.xz\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
