name: Compressor

on: [push]

env:
  FILE_URL: https://github.com/nitanmarcel/Silky-Gboard/releases/download/v0.4/gboard-silk-theme-0.4.zip 
  FILE_NAME: final-test
  TZ: Asia/Kolkata
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Setup
         run: |
           sudo -E apt-get update
           sudo apt install expect -y
           sudo apt-get install -y wget gzip

       - name: Download & Decompress File
         run: |
              mkdir -p file
              wget -U "Mozilla/5.0" $FILE_URL -O "file/$FILE_NAME.zip"
              cd file
              mkdir -p final
              unzip -q $FILE_NAME -d ./final
       
       - name: Compress and Upload 
         run: |
              cd file/final
              tar cJf --recursion $FILE_NAME.tar.xz *
              ls
              expect -c " 
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"cd ${{ secrets.SFDIR }}\r\"
              set timeout -1
              send \"put $FILE_NAME.tar.xz\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
